### PR TITLE
Fix some transparent objects rendering behind env boxes.

### LINKED ISSUE #165: Certain transparent objects render behind env boxes.
Mostly due to env boxes usually being on LAYER_TRANSPARENT_INTER.

Most noticeable on:

Trees which are close to the cutout/transparency switch threshold:
image

The flames in the castle basement:
image

Burn smoke in the LLL volcano:
image

This is technically a vanilla bug, but it is much more noticeable in HackerSM64 due to the proximity transparency, burn smoke fix, and camera angles that couldn't easily be achieved in vanilla.

### PR DESCRIPTION
**Pull request by Arceveti**
Fixes #165 

Re-opening this since it's a bugfix.

### CODE REVIEW

File: src/game/object_helpers.c [hunk 1]
```diff
@@ -62,28 +63,30 @@ Gfx *geo_update_layer_transparency(s32 callContext, struct GraphNode *node, UNUS
...
+            } else if (parameter == GEO_TRANSPARENCY_MODE_INTER) {
+                SET_GRAPH_NODE_LAYER(currentGraphNode->fnNode.node.flags, LAYER_TRANSPARENT_INTER);
             } else {
                 SET_GRAPH_NODE_LAYER(currentGraphNode->fnNode.node.flags, LAYER_TRANSPARENT);
             }
 
             objectGraphNode->oAnimState = TRANSPARENCY_ANIM_STATE_TRANSPARENT;
 
-            if (objectOpacity == 0x00 && segmented_to_virtual(bhvBowser) == objectGraphNode->behavior) {
+            if ((objectOpacity == 0x00) && segmented_to_virtual(bhvBowser) == objectGraphNode->behavior) {
```
Comment (thecozies) [inline src/game/object_helpers.c:84]: nice try
```suggestion
            if (objectOpacity == 0x00 && segmented_to_virtual(bhvBowser) == objectGraphNode->behavior) {
```

File: src/game/object_helpers.c [hunk 2]
```diff
@@ -62,28 +63,30 @@ Gfx *geo_update_layer_transparency(s32 callContext, struct GraphNode *node, UNUS
...
                 objectGraphNode->oAnimState = BOWSER_ANIM_STATE_INVISIBLE;
             }
 
-            if (currentGraphNode->parameter != GEO_TRANSPARENCY_MODE_NO_DITHER
-                && (objectGraphNode->activeFlags & ACTIVE_FLAG_DITHERED_ALPHA)) {
+            if ((parameter != GEO_TRANSPARENCY_MODE_NO_DITHER)
```
Comment (thecozies) [inline src/game/object_helpers.c:88]: nicer try
```suggestion
            if (parameter != GEO_TRANSPARENCY_MODE_NO_DITHER
```

File: src/game/object_helpers.c [hunk 3]
```diff
@@ -62,28 +63,30 @@ Gfx *geo_update_layer_transparency(s32 callContext, struct GraphNode *node, UNUS
...
+             && (objectGraphNode->activeFlags & ACTIVE_FLAG_DITHERED_ALPHA)) {
```
Comment (thecozies) [inline src/game/object_helpers.c:89]: mean try
```suggestion
            if (parameter != GEO_TRANSPARENCY_MODE_NO_DITHER
                && (objectGraphNode->activeFlags & ACTIVE_FLAG_DITHERED_ALPHA)) {
```

**Review by thecozies — CHANGES_REQUESTED** [review]
some formatting changes' changes

**Review by thecozies — APPROVED** [review]
