### PR TITLE
Re-implement POWER_STARS_HEAL for normal Power Stars

### LINKED ISSUE #209: `POWER_STARS_HEAL` Does Not Work
At a glance, it looks like this applies to the grand star only?

### PR DESCRIPTION
**Pull request by Arceveti**
Fixes #209 

This define only has a gameplay effect with non-exit stars (100 coins, Bowser red coins, etc.).

### CODE REVIEW

File: src/game/interaction.c [hunk 1]
```diff
@@ -776,12 +776,21 @@ u32 interact_star_or_key(struct MarioState *m, UNUSED u32 interactType, struct O
...
+#else // !POWER_STARS_HEAL
         if (!noExit) {
             m->hurtCounter = 0;
             m->healCounter = 0;
-#ifdef BREATH_METER
+ #ifdef BREATH_METER
             m->breathCounter = 0;
-#endif
+ #endif
+#endif // !POWER_STARS_HEAL
```
Comment (thecozies) [inline src/game/interaction.c:793]: comments denoting ifdef ends are nice

**Review by thecozies — APPROVED** [review]
