### PR TITLE
Config cleanup/refactor

### LINKED ISSUE #262: Move puppyprint define (and improve config)
- Disconnect puppyprint from puppyprint debug
- add safeguard for puppyprint debug to enable puppyprint
- enable puppyprint by default because crash screen doesnt work without it

### LINKED ISSUE #272: GFX_POOL_SIZE should be moved to config_graphics.h
Accessibility!

### PR DESCRIPTION
**Pull request by thecozies**
- Moved all config safeguards to `config_safeguards.h`
- Moved puppyprint to `config_graphics.h`
- Auto-enable puppyprint if `PUPPYPRINT_DEBUG` is enabled
- Rearranged some defines in `config_debug.h` to better reflect what is used most
- Moves `GFX_POOL_SIZE` to `config_graphics.h` #272 
- Disables `EASIER_DIALOG_TRIGGER` by default

Fixes #262
Fixes #272

### CODE REVIEW

File: include/config/config_safeguards.h [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+ * NOTE: Only mess with these if you know what you're doing!
+ * These are put in place to insure that connected functionality works as intended.
+ */
+
+
+/*****************
+ * config_graphics
+ */
+
+#ifndef F3DZEX_GBI_2
```
Comment (Mr-Wiseguy) [inline include/config/config_safeguards.h:17]: As mentioned before, this is incorrect. F3DEX2 also works with rej.

**Review by Mr-Wiseguy — APPROVED** [review]
We can leave enabled rej on f3dex2 for a later version (especially since nobody will probably actually use it), just wanted to be clear that it's not just zex that supports it.

File: include/config/config_safeguards.h (hunk 1 above)
Comment (thecozies) [reply include/config/config_safeguards.h:17]: oh yeah so this should be F3DEX_GBI_2?

**Comment by thecozies** [comment]
> We can leave enabling rej on f3dex2 for a later version (especially since nobody will probably actually use it), just wanted to be clear that it's not just zex that supports it.

sounds good, I'll make an issue for it

**Review by axollyon — COMMENTED** [review]
i like isolating the safeguards into their own file, makes it harder for somebody to accidentally mess with them

**Review by axollyon — APPROVED** [review]

File: include/config/config_safeguards.h [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+
+#ifdef DEBUG_ALL
+    #define DEBUG_LEVEL_SELECT
+    #define ENABLE_DEBUG_FREE_MOVE
+    #define PUPPYPRINT
+    #define PUPPYPRINT_DEBUG 1
+    #define VISUAL_DEBUG
+    #define UNLOCK_ALL
+    #define COMPLETE_SAVE_FILE
+#endif // DEBUG_ALL
```
Comment (gheskett) [inline include/config/config_safeguards.h:54]: If I'm not mistaken, this can also lead to compiler warnings via duplicate defines.

File: include/config/config_safeguards.h [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+#endif
+
+
+/*****************
+ * config_goddard
+ */
+
+#ifndef KEEP_MARIO_HEAD
+    #undef GODDARD_EASTER_EGG
+    #define DISABLE_DEMO
```
Comment (gheskett) [inline include/config/config_safeguards.h:112]: Also here; another compiler warning

File: include/config/config_safeguards.h [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+
+
+/*****************
+ * config_rom
+ */
+
+#ifndef TARGET_N64
+    #define BORDER_HEIGHT_CONSOLE  0
+    #define BORDER_HEIGHT_EMULATOR 0
+#endif // !TARGET_N64
```
Comment (gheskett) [inline include/config/config_safeguards.h:146]: And these too.

File: include/config/config_safeguards.h [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+    #undef DEBUG_FORCE_CRASH_ON_BOOT
+#endif // DISABLE_ALL
+
+
+/*****************
+ * config_camera
+ */
+
+#ifdef FORCED_CAMERA_MODE
+    #define USE_COURSE_DEFAULT_MODE // Forced camera mode overwrites the default mode
```
Comment (gheskett) [inline include/config/config_safeguards.h:77]: This can be defined more than once as well.

File: include/config/config_safeguards.h [hunk 6]
```diff
@@ -0,0 +1,146 @@
...
+ */
+
+#ifdef PUPPYPRINT_DEBUG
+    #ifndef PUPPYPRINT
+        #define PUPPYPRINT
+    #endif
+#endif
+
+#ifdef COMPLETE_SAVE_FILE
+    #define UNLOCK_ALL
```
Comment (gheskett) [inline include/config/config_safeguards.h:43]: UNLOCK_ALL can potentially be redefined here, which I believe causes a compiler warning.

**Review by gheskett — COMMENTED** [review]
Can somebody double check to make sure I caught everything here?

**Review by Reonu — APPROVED** [review]
Looks epic, and I really like the safeguards having their own file!
