### PR TITLE
Fix some drawing distance issues caused by AUTO_COLLISION_DISTANCE

### LINKED ISSUE #173: Pyramid Visibility
The top of the pyramid in SSL is not visible unless you are very close to it. This is hopefully just an issue with the pyramid object itself, but it could be indicative of an issue related to global render distance for objects.

### PR DESCRIPTION
**Pull request by Arceveti**
Fixes #173

Some vanilla objects use oCollisionDistance to set their oDrawingDistance (since oDrawingDistance is set to oCollisionDistance if the latter is larger). Since AUTO_COLLISION_DISTANCE makes oCollisionDistance much smaller for a lot of objects, this PR sets oDrawingDistance separately.

### CODE REVIEW

File: data/behavior_data.c [hunk 1]
```diff
@@ -2661,7 +2662,7 @@ const BehaviorScript bhvBowserSubDoor[] = {
     BEGIN(OBJ_LIST_SURFACE),
     OR_LONG(oFlags, (OBJ_FLAG_ACTIVE_FROM_AFAR | OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE | OBJ_FLAG_UCODE_LARGE)),
     LOAD_COLLISION_DATA(ddd_seg7_collision_bowser_sub_door),
-    SET_FLOAT(oDrawingDistance, 20000),
+    SET_FLOAT(oDrawingDistance,   20000),
```
Comment (axollyon) [inline data/behavior_data.c:2665]: Lots of formatting changes - are these necessary?

**Review by axollyon — DISMISSED** [review]

File: data/behavior_data.c (hunk 1 above)
Comment (Arceveti) [reply data/behavior_data.c:2665]: There were only 2 of those changes. Those were for consistency with the other places oDrawingDistance and oCollisionDistance were already used together in the file.

Comment (Mr-Wiseguy) [reply data/behavior_data.c:2665]: Please revert the formatting changes, as they'll cause merge conflicts in the future if base decomp incorporates them as well.

File: data/behavior_data.c [hunk 2]
```diff
@@ -851,6 +851,7 @@ const BehaviorScript bhvExitPodiumWarp[] = {
     OR_INT(oFlags, (OBJ_FLAG_SET_FACE_YAW_TO_MOVE_YAW | OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE)),
     SET_INT(oInteractType, INTERACT_WARP),
     DROP_TO_FLOOR(),
+    SET_FLOAT(oDrawingDistance,   8000),
```
Comment (thecozies) [inline data/behavior_data.c:854]:
```suggestion
    SET_FLOAT(oDrawingDistance, 8000),
```

File: data/behavior_data.c (hunk 1 above)
Comment (thecozies) [inline data/behavior_data.c:2665]:
```suggestion
    SET_FLOAT(oDrawingDistance, 20000),
```

File: data/behavior_data.c [hunk 3]
```diff
@@ -2672,7 +2673,7 @@ const BehaviorScript bhvBowserSubDoor[] = {
 const BehaviorScript bhvBowsersSub[] = {
     BEGIN(OBJ_LIST_SURFACE),
     OR_LONG(oFlags, (OBJ_FLAG_ACTIVE_FROM_AFAR | OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE | OBJ_FLAG_UCODE_LARGE)),
-    SET_FLOAT(oDrawingDistance, 20000),
+    SET_FLOAT(oDrawingDistance,   20000),
```
Comment (thecozies) [inline data/behavior_data.c:2676]:
```suggestion
    SET_FLOAT(oDrawingDistance, 20000),
```

File: data/behavior_data.c [hunk 4]
```diff
@@ -4478,7 +4483,7 @@ const BehaviorScript bhvBigBoulder[] = {
     OR_INT(oFlags, (OBJ_FLAG_COMPUTE_ANGLE_TO_MARIO | OBJ_FLAG_SET_FACE_YAW_TO_MOVE_YAW | OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE)),
     SET_FLOAT(oGraphYOffset, 180),
     CALL_NATIVE(bhv_big_boulder_init),
-    SET_FLOAT(oCollisionDistance, 20000),
+    SET_FLOAT(oDrawingDistance, 20000),
```
Comment (thecozies) [inline data/behavior_data.c:4486]: why did you remove collision distance?

File: src/game/behaviors/falling_rising_platform.inc.c [hunk 5]
```diff
@@ -3,9 +3,6 @@
 void bhv_squishable_platform_loop(void) {
     o->header.gfx.scale[1] = (sins(o->oBitfsPlatformTimer) + 1.0f) * 0.3f + 0.4f;
     o->oBitfsPlatformTimer += 0x80;
-#ifdef AUTO_COLLISION_DISTANCE
-    o->oFlags &= ~OBJ_FLAG_DONT_CALC_COLL_DIST;
-#endif
```
Comment (thecozies) [inline src/game/behaviors/falling_rising_platform.inc.c:8]: what was this for?

**Review by thecozies — CHANGES_REQUESTED** [review]
revert formatting changes

File: src/game/behaviors/falling_rising_platform.inc.c (hunk 5 above)
Comment (RyanPadveen) [reply src/game/behaviors/falling_rising_platform.inc.c:8]: Previously the platform recalculated collision distance every frame. This just reverts it to vanilla behavior since it has OBJ_FLAG_DONT_CALC_COL_DISTANCE now.

File: data/behavior_data.c (hunk 4 above)
Comment (RyanPadveen) [reply data/behavior_data.c:4486]: oCollisionDistance is unused for Boulders

Comment (Arceveti) [reply data/behavior_data.c:4486]: oCollisionDistance was unused for boulders

File: src/game/behaviors/falling_rising_platform.inc.c (hunk 5 above)
Comment (Arceveti) [reply src/game/behaviors/falling_rising_platform.inc.c:8]: Previously, the scaling/squishing platform recalculated its collision distance. This reverts the collision distance to vanilla since it has OBJ_FLAG_DONT_CALC_COLL_DISTANCE now.

**Comment by Arceveti** [comment]
> revert formatting changes

They've been reverted to match ultrasm64/vanilla decomp now

File: data/behavior_data.c [hunk 6]
```diff
@@ -851,6 +851,7 @@ const BehaviorScript bhvExitPodiumWarp[] = {
     OR_INT(oFlags, (OBJ_FLAG_SET_FACE_YAW_TO_MOVE_YAW | OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE)),
     SET_INT(oInteractType, INTERACT_WARP),
     DROP_TO_FLOOR(),
+    SET_FLOAT(oDrawingDistance, 8000),
```
Comment (thecozies) [inline data/behavior_data.c:854]: doesnt this need `OBJ_FLAG_DONT_CALC_COLL_DIST` to work?

File: data/behavior_data.c [hunk 7]
```diff
@@ -2721,6 +2722,7 @@ const BehaviorScript bhvInSunkenShip3[] = {
     OR_LONG(oFlags, (OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE | OBJ_FLAG_UCODE_LARGE)),
     LOAD_COLLISION_DATA(jrb_seg7_collision_in_sunken_ship_3),
     SET_HOME(),
+    SET_FLOAT(oDrawingDistance, 4000),
```
Comment (thecozies) [inline data/behavior_data.c:2725]: doesnt this need `OBJ_FLAG_DONT_CALC_COLL_DIST` to work?

File: data/behavior_data.c [hunk 8]
```diff
@@ -2766,6 +2768,7 @@ const BehaviorScript bhvInSunkenShip2[] = {
     LOAD_COLLISION_DATA(jrb_seg7_collision_in_sunken_ship_2),
     // Sunken ship - common:
     OR_LONG(oFlags, (OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE | OBJ_FLAG_UCODE_LARGE)),
+    SET_FLOAT(oDrawingDistance, 4000),
```
Comment (thecozies) [inline data/behavior_data.c:2771]: doesnt this need `OBJ_FLAG_DONT_CALC_COLL_DIST` to work?

File: data/behavior_data.c [hunk 9]
```diff
@@ -4327,6 +4330,7 @@ const BehaviorScript bhvPyramidElevator[] = {
     OR_LONG(oFlags, (OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE | OBJ_FLAG_UCODE_LARGE)),
     LOAD_COLLISION_DATA(ssl_seg7_collision_pyramid_elevator),
     SET_HOME(),
+    SET_FLOAT(oDrawingDistance, 20000),
```
Comment (thecozies) [inline data/behavior_data.c:4333]: `OBJ_FLAG_DONT_CALC_COLL_DIST`?

File: data/behavior_data.c [hunk 10]
```diff
@@ -4349,6 +4353,7 @@ const BehaviorScript bhvPyramidTop[] = {
     OR_LONG(oFlags, (OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE | OBJ_FLAG_UCODE_LARGE)),
     LOAD_COLLISION_DATA(ssl_seg7_collision_pyramid_top),
     SET_HOME(),
+    SET_FLOAT(oDrawingDistance, 20000),
```
Comment (thecozies) [inline data/behavior_data.c:4356]: `OBJ_FLAG_DONT_CALC_COLL_DIST`?

File: data/behavior_data.c (hunk 4 above)
Comment (thecozies) [reply data/behavior_data.c:4486]: how so?

Comment (thecozies) [reply data/behavior_data.c:4486]: i think this may need 20k so it can still hurt enemies right?

**Review by thecozies — COMMENTED** [review]
questions on `OBJ_FLAG_DONT_CALC_COLL_DIST` usage mostly

**Comment by Arceveti** [comment]
> questions on `OBJ_FLAG_DONT_CALC_COLL_DIST` usage mostly

oDrawingDistance only gets set to oCollisionDistance if oDrawingDistance is lower. All of those places are setting oDrawingDistance manually, so that it doesn't get changed when load_object_collision_model is called after AUTO_COLLISION_DISTANCE sets oCollisionDistance to smaller than vanilla. Using OBJ_FLAG_DONT_CALC_COLL_DIST instead would just use vanilla collision distance.

File: data/behavior_data.c (hunk 4 above)
Comment (Arceveti) [reply data/behavior_data.c:4486]: Only objects that use load_object_collision_model are affected by oCollisionDistance. Boulders use set_rolling_sphere_hitbox for their collision.

**Review by thecozies — APPROVED** [review]
# its working!
