### PR TITLE
Fixed sAudioEnabled and Puppyprint RDP times

### LINKED ISSUE #222: Profiling bugs
sAudioEnabled does not actually disable audio processing on the CPU which causes the measured performance of other systems to fluctuate wildly due to the audio thread preempting them.

RDP times displayed on the profiler screen are also inaccurate as they convert cycles to us using the CPU ratio and not the RDP ratio.

### PR DESCRIPTION
**Pull request by Mr-Wiseguy**
Fixes #222

### CODE REVIEW

File: src/audio/external.c [hunk 1]
```diff
@@ -579,6 +579,8 @@ void func_eu_802e9bec(s32 player, s32 channel, s32 arg2) {
 
 #else
 
+extern s8 sAudioEnabled;
```
Comment (thecozies) [inline src/audio/external.c:582]: this is a lil goofy since the `s` implies static, if its not too much of a pain i think it'd be nice if this was changed to `gAudioEnabled` and externed from main.h

**Review by thecozies — COMMENTED** [review]
profiling stuff looks good, just an extern comment

**Comment by aglab2** [comment]
sAudioEnabled must be under PUPPYPRINT_DEBUG, otherwise it adds extra to cpu

File: src/audio/external.c (hunk 1 above)
Comment (Mr-Wiseguy) [reply src/audio/external.c:582]: sAudioEnabled was already nonstatic to begin with. I can rename it though.

**Review by thecozies — APPROVED** [review]
looks good! don't worry about renaming, merge ahead
